### ISSUE TITLE
Missing manifest.json 

### ISSUE THREAD

**Issue by JasonEsposito** [moderatorwes/Zentastic#16]
When I tried to upload this zip file I get an error saying it's missing the manifest.json file?

**Comment by moderatorwes** [comment]
@JasonEsposito - This theme was created well before the new theming center came along so at this time there is no way to import the theme.  Back in the day it was a copy/paste job.  I would recommend that you stick with the Copenhagen theme or modify that theme to your design.  If you need help with doing that then just let me know.

**Comment by moderatorwes** [comment]
@JasonEsposito - Hold on one second I will upload the complete zip file for you to try out.

**Comment by JasonEsposito** [comment]
Haha I thought it was a long shot trying this. Thanks for the quick response too.. I was always going to create my own theme but was just looking for inspiration :)

**Comment by moderatorwes** [comment]
@JasonEsposito - Go ahead and try the zip file that I just uploaded out there.  It's older code but still should work.
