### ISSUE TITLE
'Submit a request' button not working in IE11

### ISSUE THREAD

**Issue by iMSPLimited** [moderatorwes/Zentastic#4]
Hi,

Firstly thanks for the amazing theme - a great piece of work!

Followed the install instructions to the letter and my site looks like your screenshots. all good so far.
But....
After login 'Submit a request' button works fine in Chrome but nothing happens when clicked in IE11.

Do you have any suggestions please?

Regards
J
iMSP

**Comment by moderatorwes** [comment]
Thanks for the feedback and I'll do some testing in IE 11 to see if I can duplicate the issue.  I'm currently on vacation so it will be later in the week before I get back with you.

Wes

Sent from my Windows Phone
________________________________

**Comment by iMSPLimited** [comment]
Hi Wes,
Did you have a chance to look at this yet?
Thanks in advance.
J

**Comment by moderatorwes** [comment]
I didn't see an issue on my end with IE 11 but if you are still seeing an issue you may need to apply some extra CSS.  Please make sure your bootstrap.css and bootstrap.jss files are calling the newest version.  You can find this in the Document Header.  The newest versions are:


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
