### ISSUE TITLE
Remove the 'centered' CSS class

### ISSUE THREAD

**Issue by coliff** [moderatorwes/Zentastic#6]
Could avoid some CSS duplication by removing the .centered class from the CSS and instead use the already defined text-center (http://getbootstrap.com/css/#type-alignment) or center-block (http://getbootstrap.com/css/#helper-classes-center) classes from Bootstrap

**Comment by moderatorwes** [comment]
I probably had that in there while doing some testing.  Feel free to do a pull-request if not its not hurting anything by staying in there.

Thanks for the feedback.
