### ISSUE TITLE
Theme uses components not available in Curlybars

### ISSUE THREAD

**Issue by scriptist** [moderatorwes/Zentastic#8]
Zendesk has moved their templates over to Curlybars, which unfortunately totally breaks this theme.

https://support.zendesk.com/hc/en-us/articles/209716328

**Comment by moderatorwes** [comment]
Yes I'm aware of the change and will be coping the Curlybars code.  I've already started pasting the code in, I won't publish until its all there.

**Comment by moderatorwes** [comment]
All HTML pages have now been updated.
